@addMethod(gameuiInGameMenuGameController)
protected cb func RegisterBAFFLINGBILLSBIZARREBAZAARStore(event: ref<VirtualShopRegistration>) -> Bool {
  event.AddStore(
    n"BAFFLINGBILLSBIZARREBAZAAR",
    "Baffling Bill's Bizarre Bazaar",
    ["Items.b4_luxCrystals_base", "Items.b4_luxCrystals_pulsewavePink", "Items.b4_luxCrystals_electricMana", "Items.b4_luxCrystals_electricPulseberry", "Items.b4_luxCrystals_cyberCrystals", "Items.b4_spikedChokers_punkPreemNoir", "Items.b4_spikedChokers_punkElectricPulseberry", "Items.b4_spikedChokers_punkPreemClean", "Items.b4_spikedChokers_punkPulsewavePreem", "Items.b4_spikedChokers_punkElectricDevil", "Items.b4_spikedChokers_punkUltravioletPreem", "Items.b4_spikedChokers_raverNeonGlitchcast", "Items.b4_spikedChokers_raverElectricPulseberry", "Items.b4_spikedChokers_raverGlitchchemUltraviolet", "Items.b4_spikedChokers_raverElectricDevil", "Items.b4_spikedChokers_raverBitratePulsewave", "Items.b4_spikedChokers_raverBlackwallBorder", "Items.b4_spikedChokers_rockerPreemNoir", "Items.b4_spikedChokers_rockerPreemClean", "Items.b4_spikedChokers_rockerPreemUltraviolet", "Items.b4_spikedChokers_rockerPreemPulsewave", "Items.b4_spikedChokers_rockerElectricPulseberry", "Items.b4_spikedChokers_rockerElectricDevil", "Items.b4_spikedChokers_rockerBlackwallBorder", "Items.b4_spikedChokers_rockerMeatsuitMedley", "Items.b4_spikedChokers_rockerGreenPlastic", "Items.b4_streetpunkjacket_default", "Items.b4_streetpunkjacket_badapple", "Items.b4_streetpunkjacket_silversamurai", "Items.b4_streetpunkjacket_holypearl", "Items.b4_streetpunkjacket_netwyrm", "Items.b4_streetpunkjacket_sulfuricpsycho", "Items.b4_streetpunkjacket_logodefault", "Items.b4_streetpunkjacket_logovariant1", "Items.b4_streetpunkjacket_logovariant2", "Items.b4_streetpunkjacket_logovariant3", "Items.b4_streetpunkjacket_logovariant4", "Items.b4_streetpunkjacket_logovariant5", "Items.b4_streetpunkjacket_logovariant6", "Items.b4_streetpunkjacket_logovariant7", "Items.b4_streetpunkjacket_logovariant8", "Items.b4_streetpunkjacket_logovariant9", "Items.b4_streetpunkjacket_logovariant10", "Items.b4_streetpunkjacket_logovariant11", "Items.b4_streetpunkjacket_logovariant12", "Items.b4_streetpunkjacket_logovariant13", "Items.b4_streetpunkjacket_logovariant14", "Items.b4_streetpunkjacket_logovariant15", "Items.b4_streetpunkjacket_logovariant16", "Items.b4_streetpunkjacket_logovariant17", "Items.b4_streetpunkjacket_logovariant18"],
    [300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300],
r"b4/ops/atelier_icon.inkatlas",
n"slot_01",
["Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random", "Random"],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  );
}